// The OpenNext worker is generated by `npm run cf:build` before Wrangler bundles this file.
// @ts-ignore Generated module is intentionally absent before the Cloudflare build.
import handler from './.open-next/worker.js'

type ScheduledEventLike = {
  cron: string
  scheduledTime: number
}

type ExecutionContextLike = {
  waitUntil(promise: Promise<unknown>): void
  passThroughOnException(): void
}

type WorkerEnvironment = Record<string, unknown> & {
  CRON_JOBS_ENABLED?: string
  CRON_SECRET?: string
}

type ScheduledJob = {
  method: 'GET' | 'POST'
  path: string
  name: string
}

const INTERNAL_ORIGIN = 'https://9jadirectory.internal'

async function runScheduledJob(
  job: ScheduledJob,
  env: WorkerEnvironment,
  ctx: ExecutionContextLike
) {
  const response = await handler.fetch(
    new Request(`${INTERNAL_ORIGIN}${job.path}`, {
      method: job.method,
      headers: {
        authorization: `Bearer ${env.CRON_SECRET}`,
        'x-9jadirectory-scheduled-job': job.name,
      },
    }),
    env,
    ctx
  )

  if (!response.ok) {
    const body = await response.text()
    throw new Error(`${job.name} failed with ${response.status}: ${body.slice(0, 500)}`)
  }
}

export default {
  fetch: handler.fetch,

  async scheduled(
    event: ScheduledEventLike,
    env: WorkerEnvironment,
    ctx: ExecutionContextLike
  ) {
    // Staging receives the trigger but performs no database or email mutations.
    // Set this to "true" only after all production secrets and smoke tests pass.
    if (env.CRON_JOBS_ENABLED !== 'true') {
      console.log('Scheduled jobs are disabled for this deployment.')
      return
    }

    if (!env.CRON_SECRET) {
      throw new Error('CRON_SECRET is required when scheduled jobs are enabled.')
    }

    const scheduledAt = new Date(event.scheduledTime)
    const minute = scheduledAt.getUTCMinutes()
    const hour = scheduledAt.getUTCHours()
    const jobs: ScheduledJob[] = []

    // Mark stale pending payments once per hour.
    if (minute === 0) {
      jobs.push({
        method: 'GET',
        path: '/api/cron/abandon-payments',
        name: 'abandon-payments',
      })
    }

    // Expire paid promotions once per day at 00:00 UTC (01:00 Lagos).
    if (minute === 0 && hour === 0) {
      jobs.push({
        method: 'GET',
        path: '/api/cron/expire-featured',
        name: 'expire-featured',
      })
    }

    // Deliver queued account and moderation emails every 15 minutes.
    jobs.push({
      method: 'POST',
      path: '/api/send-emails',
      name: 'send-emails',
    })

    for (const job of jobs) {
      await runScheduledJob(job, env, ctx)
    }
  },
}

// Required when the generated OpenNext worker enables either durable object.
// @ts-ignore Generated module is intentionally absent before the Cloudflare build.
export { DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js'
