-- Import ALL 90 Listings for 9jaDirectory
-- Generated from CSV
-- Run this in Supabase SQL Editor after running database-schema-enhanced.sql

-- Insert all listings
INSERT INTO listings (
  business_name,
  slug,
  description,
  category_id,
  state_id,
  city_id,
  address,
  phone,
  established_year,
  status,
  verified,
  created_at,
  updated_at
) VALUES
-- Row 1: Macmed Integrated Farms
(
  'Macmed Integrated Farms',
  'macmed-integrated-farms-1',
  'Sustainable farming and livestock solutions with comprehensive planning services.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '1, Gani Street, Ijegun Imore. Satellite Town, Lagos, Lagos, Nigeria',
  '+2348033316905',
  2013,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 2: Aerologistics and Travels Ltd
(
  'Aerologistics and Travels Ltd',
  'aerologistics-and-travels-ltd-2',
  'Global travel solutions: tickets, tours, logistics, training services.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  'Suite C247 Ikota Business Complex, Lagos, Lagos, Nigeria',
  '+2344610300',
  2006,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 3: Jacio International Company Ltd
(
  'Jacio International Company Ltd',
  'jacio-international-company-ltd-3',
  'Distributors of premium automotive products in Nigeria.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  'Zone B, Block 9, Shop 15, Aspamda Trade Fair Complex Lagos, Nigeria',
  '08185587222',
  2008,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 4: Maldini Granites and Marble Imports Limited
(
  'Maldini Granites and Marble Imports Limited',
  'maldini-granites-and-marble-imports-limited-4',
  'Quality granite and marble slabs, nationwide distribution in Nigeria.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'surulere' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '41A Alhaji Tokan street, Alaka Estate, Surulere, Lagos, Lagos, Nigeria',
  '+2348033079719',
  1997,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 5: COHBS International
(
  'COHBS International',
  'cohbs-international-5',
  'Your trusted source for chemical materials and supplies.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '14, Fadeyi Aladura Street, Off Awolowo Way, Ikeja Lagos Nigeria',
  '08170417114',
  2017,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 6: Auto Auction Mall
(
  'Auto Auction Mall',
  'auto-auction-mall-6',
  'Access U.S. dealer auctions for affordable vehicles made easy.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'yaba' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '268, Herbert Macaulay Way, Alagomeji, Yaba, Lagos, Lagos, Nigeria',
  '+2349015362533',
  2016,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 7: Royal Xtasy Spa
(
  'Royal Xtasy Spa',
  'royal-xtasy-spa-7',
  '24-hour massage and wellness spa in Lagos, Nigeria.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  'House 17, Transit Village, Adetokunbo Ademola Street, Victoria Island , Lagos, Lagos, Nigeria',
  '+2349043094708',
  2021,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 8: CompareForexBrokers.ng
(
  'CompareForexBrokers.ng',
  'compareforexbrokers-ng-8',
  'Your trusted guide for comparing Forex and CFDs brokers.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '196B Awolowo Rd, Lagos, Nigeria',
  '+2348115028665',
  2023,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 9: Favoured Pearls School
(
  'Favoured Pearls School',
  'favoured-pearls-school-9',
  'Nurturing young minds with quality education and care.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '4, Dapo Adeoye Street, Off Deeper Life Church, Soluyi, Gbagada, Lagos, Abia, Nigeria',
  '+2348035534097',
  NULL,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 10: EB World
(
  'EB World',
  'eb-world-10',
  'Power tools and accessories for every building project.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '497, Ikorodu Road, Ile-Ile Bus Stop, Ketu, Lagos, Lagos, Nigeria',
  '+2347030070996',
  2018,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 11: Green Valley Agro Ltd
(
  'Green Valley Agro Ltd',
  'green-valley-agro-ltd-11',
  'Organic farming, poultry and fishery solutions for sustainable agriculture.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '23, Farm Settlement Road, Ikorodu, Lagos, Nigeria',
  '+2348024457890',
  2015,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 12: Swift Travels Agency
(
  'Swift Travels Agency',
  'swift-travels-agency-12',
  'Affordable flight bookings, visa assistance, and travel packages.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '12B, Allen Avenue, Ikeja, Lagos, Nigeria',
  '+2348091234567',
  2010,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 13: TopTech Solutions
(
  'TopTech Solutions',
  'toptech-solutions-13',
  'IT consulting, software development, and digital transformation services.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'yaba' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '456, Herbert Macaulay Way, Yaba, Lagos, Nigeria',
  '+2348139876543',
  2019,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 14: Prime Properties Ltd
(
  'Prime Properties Ltd',
  'prime-properties-ltd-14',
  'Luxury real estate sales, rentals, and property management in Lagos.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'lekki' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '78, Admiralty Way, Lekki Phase 1, Lagos, Nigeria',
  '+2348065432109',
  2012,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 15: EduCare Academy
(
  'EduCare Academy',
  'educare-academy-15',
  'Quality primary and secondary education with modern facilities.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'surulere' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '5, Church Street, Surulere, Lagos, Nigeria',
  '+2348052345678',
  2008,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 16: FreshFarms Nigeria
(
  'FreshFarms Nigeria',
  'freshfarms-nigeria-16',
  'Fresh produce supplier, vegetable farming, and agricultural consulting.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  'Plot 45, Agric Settlement, Ikorodu, Lagos, Nigeria',
  '+2348076543210',
  2014,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 17: SkyHigh Logistics
(
  'SkyHigh Logistics',
  'skyhigh-logistics-17',
  'Freight forwarding, cargo services, and international shipping solutions.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '89, Apapa-Oshodi Expressway, Lagos, Nigeria',
  '+2348087654321',
  2017,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 18: MaxPro Engineering
(
  'MaxPro Engineering',
  'maxpro-engineering-18',
  'Mechanical engineering, fabrication, and industrial maintenance services.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '34, Industrial Estate, Ikeja, Lagos, Nigeria',
  '+2348108765432',
  2011,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 19: Urban Homes
(
  'Urban Homes',
  'urban-homes-19',
  'Affordable housing development and real estate investment opportunities.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'lekki' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '15, Fola Osibo Street, Lekki Phase 1, Lagos, Nigeria',
  '+2348123456789',
  2016,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 20: Bright Stars School
(
  'Bright Stars School',
  'bright-stars-school-20',
  'Nursery and primary school with focus on academic excellence.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '22, College Road, Ogba, Lagos, Nigeria',
  '+2348144567890',
  2009,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 21: AgriTech Ventures
(
  'AgriTech Ventures',
  'agritech-ventures-21',
  'Agricultural technology, smart farming solutions, and crop management.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '67, Lagos-Ibadan Expressway, Lagos, Nigeria',
  '+2348155678901',
  2018,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 22: Global Wings Travel
(
  'Global Wings Travel',
  'global-wings-travel-22',
  'Corporate travel management, event planning, and tour packages.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '3rd Floor, 123 Broad Street, Lagos Island, Nigeria',
  '+2348166789012',
  2007,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 23: ProServe Consulting
(
  'ProServe Consulting',
  'proserve-consulting-23',
  'Business consulting, HR services, and management advisory.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '28, Opebi Road, Ikeja, Lagos, Nigeria',
  '+2348177890123',
  2013,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 24: Legacy Estates
(
  'Legacy Estates',
  'legacy-estates-24',
  'Premium property development and real estate consultancy services.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'lekki' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '41, Admiralty Road, Lekki, Lagos, Nigeria',
  '+2348188901234',
  2015,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 25: Knowledge Hub
(
  'Knowledge Hub',
  'knowledge-hub-25',
  'Adult education, professional training, and certification programs.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '9, Toyin Street, Ikeja, Lagos, Nigeria',
  '+2348199012345',
  2010,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 26: Golden Harvest Farms
(
  'Golden Harvest Farms',
  'golden-harvest-farms-26',
  'Cassava farming, processing, and agricultural product distribution.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  'Plot 12, Epe Road, Lagos, Nigeria',
  '+2348200123456',
  2016,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 27: Wanderlust Tours
(
  'Wanderlust Tours',
  'wanderlust-tours-27',
  'Luxury travel experiences, safari tours, and vacation planning.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikoyi' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '56, Awolowo Road, Ikoyi, Lagos, Nigeria',
  '+2348211234567',
  2012,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 28: TechFix Solutions
(
  'TechFix Solutions',
  'techfix-solutions-28',
  'Computer repairs, phone repairs, and IT support services.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '18, Computer Village, Ikeja, Lagos, Nigeria',
  '+2348222345678',
  2020,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 29: Crown Properties
(
  'Crown Properties',
  'crown-properties-29',
  'Commercial property leasing and real estate investment advisory.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '72, Ajose Adeogun Street, Victoria Island, Lagos, Nigeria',
  '+2348233456789',
  2014,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 30: Future Leaders Academy
(
  'Future Leaders Academy',
  'future-leaders-academy-30',
  'Secondary school with STEM focus and modern learning facilities.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '31, Mobolaji Bank Anthony Way, Ikeja, Lagos, Nigeria',
  '+2348244567890',
  2011,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 31: AgroPlus Enterprises
(
  'AgroPlus Enterprises',
  'agroplus-enterprises-31',
  'Animal feed production, livestock farming, and veterinary services.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '88, Badagry Expressway, Lagos, Nigeria',
  '+2348255678901',
  2017,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 32: Journey Makers Travel
(
  'Journey Makers Travel',
  'journey-makers-travel-32',
  'Study abroad programs, immigration services, and travel documentation.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '14, Adeola Odeku Street, Victoria Island, Lagos, Nigeria',
  '+2348266789012',
  2009,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 33: Elite Services Ltd
(
  'Elite Services Ltd',
  'elite-services-ltd-33',
  'Facility management, cleaning services, and maintenance contracts.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '49, Allen Avenue, Ikeja, Lagos, Nigeria',
  '+2348277890123',
  2015,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 34: Metro Homes
(
  'Metro Homes',
  'metro-homes-34',
  'Residential property sales and rental property management.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'lekki' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '25, Lekki-Epe Expressway, Ajah, Lagos, Nigeria',
  '+2348288901234',
  2013,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 35: Smart Kids School
(
  'Smart Kids School',
  'smart-kids-school-35',
  'Montessori education and early childhood development programs.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '17, Ogudu Road, Ojota, Lagos, Nigeria',
  '+2348299012345',
  2008,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 36: FarmTech Nigeria
(
  'FarmTech Nigeria',
  'farmtech-nigeria-36',
  'Agricultural machinery, irrigation systems, and farm equipment.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  'Plot 23, Agbara Industrial Estate, Lagos, Nigeria',
  '+2348300123456',
  2019,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 37: Explore Africa Travel
(
  'Explore Africa Travel',
  'explore-africa-travel-37',
  'African safari tours, cultural experiences, and adventure travel.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'lekki' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '38, Admiralty Way, Lekki, Lagos, Nigeria',
  '+2348311234567',
  2011,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 38: ProClean Services
(
  'ProClean Services',
  'proclean-services-38',
  'Professional cleaning, fumigation, and pest control services.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'maryland' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '11, Ikorodu Road, Maryland, Lagos, Nigeria',
  '+2348322345678',
  2016,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 39: Prestige Realty
(
  'Prestige Realty',
  'prestige-realty-39',
  'Luxury real estate, property valuation, and investment consulting.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '53, Adeola Hopewell Street, Victoria Island, Lagos, Nigeria',
  '+2348333456789',
  2012,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 40: Excel Academy
(
  'Excel Academy',
  'excel-academy-40',
  'Secondary school with focus on science and technology education.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '44, Ago Palace Way, Okota, Lagos, Nigeria',
  '+2348344567890',
  2010,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 41: Green Fields Agro
(
  'Green Fields Agro',
  'green-fields-agro-41',
  'Greenhouse farming, hydroponics, and organic vegetable production.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  'Plot 56, Lagos-Abeokuta Expressway, Lagos, Nigeria',
  '+2348355678901',
  2015,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 42: Vacation Masters
(
  'Vacation Masters',
  'vacation-masters-42',
  'Holiday packages, honeymoon planning, and group travel services.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '29, Sanusi Fafunwa Street, Victoria Island, Lagos, Nigeria',
  '+2348366789012',
  2013,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 43: QuickFix Engineers
(
  'QuickFix Engineers',
  'quickfix-engineers-43',
  'Electrical engineering, plumbing, and general contracting services.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '66, Iyana Ipaja Road, Lagos, Nigeria',
  '+2348377890123',
  2018,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 44: Landmark Properties
(
  'Landmark Properties',
  'landmark-properties-44',
  'Property development, sales, and real estate marketing services.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '19, Ozumba Mbadiwe Avenue, Victoria Island, Lagos, Nigeria',
  '+2348388901234',
  2014,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 45: Pinnacle School
(
  'Pinnacle School',
  'pinnacle-school-45',
  'British curriculum school with international standard facilities.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '7, CMD Road, Magodo, Lagos, Nigeria',
  '+2348399012345',
  2009,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 46: Agro Ventures Ltd
(
  'Agro Ventures Ltd',
  'agro-ventures-ltd-46',
  'Fish farming, aquaculture, and seafood processing services.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  'Plot 34, Ojo Industrial Area, Lagos, Nigeria',
  '+2348400123456',
  2016,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 47: TravelPro Agency
(
  'TravelPro Agency',
  'travelpro-agency-47',
  'Business travel services, conference planning, and group bookings.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '51, Awolowo Way, Ikeja, Lagos, Nigeria',
  '+2348411234567',
  2012,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 48: HomeFix Services
(
  'HomeFix Services',
  'homefix-services-48',
  'Home repairs, renovation, and interior decoration services.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '22, Agege Motor Road, Lagos, Nigeria',
  '+2348422345678',
  2017,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 49: Dream Homes Ltd
(
  'Dream Homes Ltd',
  'dream-homes-ltd-49',
  'High-end property sales and luxury home development.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikoyi' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '36, Glover Road, Ikoyi, Lagos, Nigeria',
  '+2348433456789',
  2013,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 50: Victory Academy
(
  'Victory Academy',
  'victory-academy-50',
  'Affordable quality education with strong moral foundation.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '13, Idimu Road, Ikotun, Lagos, Nigeria',
  '+2348444567890',
  2011,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 51: Harvest Time Farms
(
  'Harvest Time Farms',
  'harvest-time-farms-51',
  'Fruit farming, citrus production, and agricultural exports.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'lekki' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  'Plot 78, Ibeju-Lekki, Lagos, Nigeria',
  '+2348455678901',
  2018,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 52: Adventure Travels
(
  'Adventure Travels',
  'adventure-travels-52',
  'Outdoor adventures, camping trips, and hiking expeditions.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '42, Oduduwa Crescent, GRA Ikeja, Lagos, Nigeria',
  '+2348466789012',
  2010,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 53: Total Solutions Ltd
(
  'Total Solutions Ltd',
  'total-solutions-ltd-53',
  'Business process outsourcing and customer service solutions.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '27, Kudirat Abiola Way, Ikeja, Lagos, Nigeria',
  '+2348477890123',
  2015,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 54: Prime Realty Group
(
  'Prime Realty Group',
  'prime-realty-group-54',
  'Real estate brokerage and property investment advisory.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '61, Adetokunbo Ademola Street, Victoria Island, Lagos, Nigeria',
  '+2348488901234',
  2014,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 55: Champions School
(
  'Champions School',
  'champions-school-55',
  'Day and boarding school with excellent academic track record.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '8, Ejigbo Road, Lagos, Nigeria',
  '+2348499012345',
  2012,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 56: Dairy Fresh Farms
(
  'Dairy Fresh Farms',
  'dairy-fresh-farms-56',
  'Dairy farming, milk processing, and yogurt production.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  'Plot 90, Ikorodu-Sagamu Road, Lagos, Nigeria',
  '+2348500123456',
  2017,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 57: Global Destinations
(
  'Global Destinations',
  'global-destinations-57',
  'International travel, visa processing, and travel insurance.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '55, Isaac John Street, GRA Ikeja, Lagos, Nigeria',
  '+2348511234567',
  2011,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 58: AllPro Services
(
  'AllPro Services',
  'allpro-services-58',
  'Security services, CCTV installation, and access control systems.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '33, Acme Road, Ogba, Lagos, Nigeria',
  '+2348522345678',
  2016,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 59: Summit Properties
(
  'Summit Properties',
  'summit-properties-59',
  'Estate development and property portfolio management.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikoyi' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '47, Kingsway Road, Ikoyi, Lagos, Nigeria',
  '+2348533456789',
  2013,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 60: Rising Stars School
(
  'Rising Stars School',
  'rising-stars-school-60',
  'Nursery, primary and secondary education with ICT integration.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '20, Akowonjo Road, Egbeda, Lagos, Nigeria',
  '+2348544567890',
  2010,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 61: AgriSupply Hub
(
  'AgriSupply Hub',
  'agrisupply-hub-61',
  'Agricultural inputs supplier, seeds, fertilizers, and chemicals.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ajah' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  'Plot 45, Ajah-Epe Expressway, Lagos, Nigeria',
  '+2348555678901',
  2018,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 62: Skyline Travels
(
  'Skyline Travels',
  'skyline-travels-62',
  'Flight bookings, hotel reservations, and travel packages.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '26, Oyin Jolayemi Street, Victoria Island, Lagos, Nigeria',
  '+2348566789012',
  2012,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 63: Expert Consultants
(
  'Expert Consultants',
  'expert-consultants-63',
  'Management consulting, training, and organizational development.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '39, Obafemi Awolowo Way, Ikeja, Lagos, Nigeria',
  '+2348577890123',
  2015,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 64: Urban Realty
(
  'Urban Realty',
  'urban-realty-64',
  'Property sales, lettings, and real estate advisory services.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '24, Akin Adesola Street, Victoria Island, Lagos, Nigeria',
  '+2348588901234',
  2014,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 65: Genius Academy
(
  'Genius Academy',
  'genius-academy-65',
  'Tutorial center and after-school programs for students.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'surulere' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '16, Bode Thomas Street, Surulere, Lagos, Nigeria',
  '+2348599012345',
  2011,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 66: Poultry Pro Farms
(
  'Poultry Pro Farms',
  'poultry-pro-farms-66',
  'Commercial poultry farming, egg production, and hatchery services.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  'Plot 67, Agege-Otta Road, Lagos, Nigeria',
  '+2348600123456',
  2016,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 67: Journeys Unlimited
(
  'Journeys Unlimited',
  'journeys-unlimited-67',
  'Cruise bookings, destination weddings, and luxury travel.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '43, Adeola Odeku Street, Victoria Island, Lagos, Nigeria',
  '+2348611234567',
  2013,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 68: TopNotch Services
(
  'TopNotch Services',
  'topnotch-services-68',
  'Event planning, catering, and hospitality management.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'maryland' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '30, Mobolaji Bank Anthony Way, Maryland, Lagos, Nigeria',
  '+2348622345678',
  2017,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 69: Horizon Properties
(
  'Horizon Properties',
  'horizon-properties-69',
  'Real estate development and construction services.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '52, Kofo Abayomi Street, Victoria Island, Lagos, Nigeria',
  '+2348633456789',
  2012,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 70: Future Bright School
(
  'Future Bright School',
  'future-bright-school-70',
  'Christian-based education with character development focus.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '21, Egbeda-Idimu Road, Lagos, Nigeria',
  '+2348644567890',
  2010,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 71: Crop Masters Ltd
(
  'Crop Masters Ltd',
  'crop-masters-ltd-71',
  'Crop cultivation, processing, and agricultural commodities trading.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'lekki' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  'Plot 89, Lekki Free Trade Zone, Lagos, Nigeria',
  '+2348655678901',
  2019,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 72: Travel Express
(
  'Travel Express',
  'travel-express-72',
  'Bus ticketing, cargo services, and interstate travel.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '37, Adeniyi Jones Avenue, Ikeja, Lagos, Nigeria',
  '+2348666789012',
  2011,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 73: ProTech Solutions
(
  'ProTech Solutions',
  'protech-solutions-73',
  'Software development, web design, and digital marketing.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '48, Computer Village, Ikeja, Lagos, Nigeria',
  '+2348677890123',
  2016,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 74: Elite Estates
(
  'Elite Estates',
  'elite-estates-74',
  'Luxury property development and high-end real estate sales.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '35, Ahmadu Bello Way, Victoria Island, Lagos, Nigeria',
  '+2348688901234',
  2013,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 75: Knowledge Academy
(
  'Knowledge Academy',
  'knowledge-academy-75',
  'JAMB/WAEC preparation classes and educational consulting.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '10, Festac Link Road, Amuwo Odofin, Lagos, Nigeria',
  '+2348699012345',
  2012,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 76: FarmPlus Nigeria
(
  'FarmPlus Nigeria',
  'farmplus-nigeria-76',
  'Integrated farming, crop and livestock production systems.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  'Plot 12, Agbara-Badagry Road, Lagos, Nigeria',
  '+2348700123456',
  2015,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 77: Passport Travels
(
  'Passport Travels',
  'passport-travels-77',
  'Passport services, visa facilitation, and travel advisory.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '32, Allen Avenue, Ikeja, Lagos, Nigeria',
  '+2348711234567',
  2014,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 78: MegaServe Ltd
(
  'MegaServe Ltd',
  'megaserve-ltd-78',
  'Logistics, courier services, and supply chain management.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '40, Oba Akran Avenue, Ikeja, Lagos, Nigeria',
  '+2348722345678',
  2018,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 79: Capital Homes
(
  'Capital Homes',
  'capital-homes-79',
  'Residential and commercial property development and sales.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '58, Ajose Adeogun Street, Victoria Island, Lagos, Nigeria',
  '+2348733456789',
  2015,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 80: Scholars Academy
(
  'Scholars Academy',
  'scholars-academy-80',
  'Quality education with focus on STEM and entrepreneurship.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '15, Ipaja-Ayobo Road, Lagos, Nigeria',
  '+2348744567890',
  2009,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 81: AgroMax Ventures
(
  'AgroMax Ventures',
  'agromax-ventures-81',
  'Agricultural consultancy, farm management, and agribusiness.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  'Plot 23, Epe-Ijebu Ode Road, Lagos, Nigeria',
  '+2348755678901',
  2017,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 82: World Travelers
(
  'World Travelers',
  'world-travelers-82',
  'Tour operations, travel packages, and destination management.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '46, Karimu Kotun Street, Victoria Island, Lagos, Nigeria',
  '+2348766789012',
  2010,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 83: Excellence Services
(
  'Excellence Services',
  'excellence-services-83',
  'HR outsourcing, recruitment, and staffing solutions.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikoyi' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '28, Awolowo Road, Ikoyi, Lagos, Nigeria',
  '+2348777890123',
  2013,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 84: Gateway Properties
(
  'Gateway Properties',
  'gateway-properties-84',
  'Property management, facility management, and leasing services.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '50, Ozumba Mbadiwe Avenue, Victoria Island, Lagos, Nigeria',
  '+2348788901234',
  2016,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 85: Premier Academy Lagos
(
  'Premier Academy Lagos',
  'premier-academy-lagos-85',
  'International school with A-Level and IGCSE programs.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '6, Bishop Oluwole Street, Victoria Island, Lagos, Nigeria',
  '+2348799012345',
  2008,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 86: Agri-Business Hub
(
  'Agri-Business Hub',
  'agri-business-hub-86',
  'Agricultural training, farm setup, and agribusiness consulting.',
  (SELECT id FROM categories WHERE slug = 'agriculture' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  'Plot 34, Lagos-Badagry Expressway, Lagos, Nigeria',
  '+2348800123456',
  2018,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 87: Fly High Travels
(
  'Fly High Travels',
  'fly-high-travels-87',
  'Corporate travel, MICE services, and travel technology solutions.',
  (SELECT id FROM categories WHERE slug = 'transportation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '31, Idowu Taylor Street, Victoria Island, Lagos, Nigeria',
  '+2348811234567',
  2012,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 88: Best Services Ltd
(
  'Best Services Ltd',
  'best-services-ltd-88',
  'Branding, printing, and advertising services for businesses.',
  (SELECT id FROM categories WHERE slug = 'professional-services' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'ikeja' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '19, Oregun Road, Ikeja, Lagos, Nigeria',
  '+2348822345678',
  2015,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 89: Prestige Homes Ltd
(
  'Prestige Homes Ltd',
  'prestige-homes-ltd-89',
  'Upscale property sales and real estate investment opportunities.',
  (SELECT id FROM categories WHERE slug = 'real-estate' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  (SELECT id FROM cities WHERE slug = 'victoria-island' AND state_id = (SELECT id FROM states WHERE slug = 'lagos') LIMIT 1),
  '45, Adeola Hopewell Street, Victoria Island, Lagos, Nigeria',
  '+2348833456789',
  2014,
  'approved',
  false,
  NOW(),
  NOW()
),
-- Row 90: Excellence Academy
(
  'Excellence Academy',
  'excellence-academy-90',
  'Comprehensive education from nursery to secondary level.',
  (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  NULL,
  '12, Akowonjo-Shasha Road, Lagos, Nigeria',
  '+2348844567890',
  2011,
  'approved',
  false,
  NOW(),
  NOW()
);

-- Verification queries
SELECT COUNT(*) as total_listings FROM listings WHERE status = 'approved';

SELECT c.name, COUNT(l.id) as count
FROM listings l
JOIN categories c ON l.category_id = c.id
GROUP BY c.name
ORDER BY count DESC;

SELECT business_name, phone, address
FROM listings
ORDER BY created_at DESC
LIMIT 10;
