-- Import 100 Business Listings from Amina CSV
-- Run this in Supabase SQL Editor
-- Generated on 2025-11-03

-- Step 1: Add missing categories
INSERT INTO categories (name, slug, icon, description) VALUES
('Accommodation', 'accommodation', '🏨', 'Hotels, lodges, guest houses, and accommodation services'),
('Automotive', 'automotive', '🚗', 'Car dealers, auto repairs, spare parts, and vehicle services'),
('Arts & Culture', 'arts-culture', '🎨', 'Art galleries, craft centers, cultural centers, and creative services'),
('Sports & Recreation', 'sports-recreation', '⚽', 'Sports clubs, fitness centers, sports management, and recreation')
ON CONFLICT (slug) DO NOTHING;

-- Step 2: Insert all 100 business listings
INSERT INTO listings (
  business_name,
  slug,
  description,
  category_id,
  state_id,
  address,
  phone,
  status,
  verified,
  created_at,
  updated_at
) VALUES
-- Accommodation Businesses (26 listings)
(
  'Nevada Hotels and Suites',
  'nevada-hotels-and-suites',
  'We offer a complete experience of standard and state-of-the art guest facilities and cuisine to inspire and please demanding food cravings. Nevada adds a perfect hospitality solution to business and leisure visitors.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '3 Aaron Irabor St, off Alh. Prince Raufu Ishola Lemomu Street, Agungi, Lekki 106104, Lagos',
  '0904 473 6776',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Chesney Hotel',
  'chesney-hotel',
  'Chesney Hotel is an oasis of luxury hotel strategically located in the heart of Lagos for great lodging accommodation with state-of-the-arts facilities to suit all clients.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '37, Saka Tinubu Street, Victoria Island, Lagos, Nigeria',
  '0909 685 1899',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'DeRitz Hotel',
  'deritz-hotel',
  'DeRitz Hotel is located in Ikeja, Lagos and they provides affordable room service with delicious food in our restaurants and at banquets.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '4 Tiwalade Close, Allen Avenue, Ikeja, Lagos, Nigeria',
  '0802 135 2167',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Protea Hotels',
  'protea-hotels',
  'Protea Hotels is a luxurious 4-star hotel located in Ikeja known to be an embodiment of class for kind of services they provide such as executive room services with Wi-Fi access and gym, swimming pool, restaurant etc.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  'Plot 2, Assbifi Road, Ikeja, Lagos, Nigeria',
  '0 1 631 0250',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Sofitel Moorhouse Hotel',
  'sofitel-moorhouse-hotel',
  'Sofitel Moorhouse Hotel is a luxury hotel in Ikoyi, Lagos that is committed to providing home away luxury room services, restaurant services and related others.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '1 Bankole Oki road, Ikoyi, Lagos, Nigeria',
  '0708 427 7309',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Welcome Centre Hotels',
  'welcome-centre-hotels',
  'Welcome Centre Hotels is a cosy hotel located in a tranquil area in Ikeja offering lodging accommodation with lots of  other facilities such as conference hall, wedding hall, leisure facilities and others.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '70 International Airport Road, Ikeja, Lagos, Nigeria',
  '0805 476 3801',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Morning Side Suites',
  'morning-side-suites',
  'Morning Side Suites is a four star hotel that offers full accomodation services with modern facilities like events hall, equipped gym, bar, restaurant and serviced rooms.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '11b Taslim Elias Close, Victoria Island, Lagos',
  '0704 643 6379',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'The Art Hotel',
  'the-art-hotel',
  'The Art Hotel provides well decorated rooms annd suites, dining, meetings and events halls, gym and art gallery.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  'Plot 13A, Block III Yesufu Abiodun Oniru Way, Victoria Island, Lagos, Nigeria',
  '0916 610 5381',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Tudor House Hotel',
  'tudor-house-hotel',
  'Tudor House Hotel offers luxurious rooms, incredible dining experience at a pocket friendly rate.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '14 Dr Adewale Oshin St, Prince Bode Adebowale Crescent, Off Chief Collins Uchiejuno, Lekki Phase 1, Lagos, Nigeria',
  '0818 004 8923',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Villa Angelia Hotels',
  'villa-angelia-hotels',
  'Villa Angelia Hotels provides hospitality needs at afforable rate, featuring standard room and double executive suite.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  'Villa Angelia, VI 20, Ojuolobun Close off Bishop Oluwole, Victoria Island, Lagos, Nigeria',
  '0909 080 2422',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'White Orchid Hotel',
  'white-orchid-hotel',
  'White Orchid Hotel is a serene hotel with a luxury accomdation services such as turaka rooftop restaurant, Jinja garden, luxury cinema and modern facilities.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '1637 Adetokunbo Ademola Street, Victoria Island, Lagos, Nigeria',
  '0901 200 2206',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Berry and Bricks Apartment',
  'berry-and-bricks-apartment',
  'Berry and bricks apartment is a 5 bedroom fully furnished luxury shortlet located in a serene and fully secured gated estate.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '1, James Anyaeche, Bera Estate, Chevron Drive, Lekki, Lagos',
  '0816 480 4088',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Cadebridge Homes',
  'cadebridge-homes',
  'Cadebridgehomes is an expertise property development and management company with activities in Nigeria and Africa. Experience our premium luxury accommodations, homes and realestate.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '15 Awolowo rd, Ikoyi, Lagos State',
  '0807 404 9468',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Autocera Homes',
  'autocera-homes',
  'Autocera homes are real estate developers providing different real estate properties, with shortlets, apartments, vacation rentals and Airbnb real estate.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '24 Glover Rd., Ikoyi Lagos, Lagos State',
  '0707 025 3975',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Alafia Honestay',
  'alafia-honestay',
  'Alafia Homestay is an oasis of calm in the midst of this bustling city, providing unique and affordable short and long-term bookings at our staycation destination located in Ogudu, Lagos.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '74A Ogudu road,. Next to Area H Police station, Ogudu GRA, Lagos',
  '0703 109 0165',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Bec Suites',
  'bec-suites',
  'Bec Suites is located in Ikeja, Lagos.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '16, Joel Ogunnaike Street / X51A & 53 Sir Michael Otedola Crescent, G.R.A, Ikeja, Lagos, Nigeria',
  '08034035514',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Chez Moi Apartment',
  'chez-moi-apartment',
  'Chez Moi Apartment contemporary living rooms with sofa beds, dining tables and 32 inch LCD flat screen televisions multi channels and DSTV.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '12 Ayoola Cooker Street, G.R.A, Ikeja, Lagos, Nigeria',
  '0815 423 7201',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Embassy Court Hotel',
  'embassy-court-hotel',
  'Embassy Court Hotel is located in Victoria Island, Lagos.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '15A Admiralty Way, Lekki Phase 1, Victoria Island, Lagos, Nigeria',
  '08033700063',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Find Nigeria Property',
  'find-nigeria-property',
  'Find Nigeria Property is an internet portal where you can find properties anywhere in Nigeria or make a request or we will find it for you.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  'Mobolaji Bank Anthony Way, Ikeja, Lagos, Nigeria',
  '0805 790 9314',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'GrandBee Suites',
  'grandbee-suites',
  'GrandBee Suites is located in Ikeja, Lagos.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '31A, Joel Ogunnaike Street, Ikeja, Lagos, Nigeria',
  '08032761206',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Hillcrest Hotel',
  'hillcrest-hotel',
  'Hillcrest Hotel are a hospitality center in Lagos for luxurious lodging, banqueting, bar and conferencing services.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '2, Afolabi Awosanya Street, Opebi, Ikeja, Lagos, Nigeria',
  '07098111180',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Hotel 1960 Eagles Park',
  'hotel-1960-eagles-park',
  'hotel 1960 eagles park is located in Ikeja and strives to meet with customers expectations in the areas of luxury guest rooms, restaurant, cocktail bar, room service and 24 hour front desk staff.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '7 Obokun Close, Awolowo way, Ikeja, Lagos, Nigeria',
  '0808 374 5991',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Oakwood Park Hotels',
  'oakwood-park-hotels',
  'Oakwood Park Hotels is located in Lekki Peninsula, Lagos.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  'Lekki Expressway, Lekki, Lagos, Nigeria',
  '08074497177',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Olatunde Kehinde & Co',
  'olatunde-kehinde-co',
  'Olatunde Kehinde & Co operations is sourcing for reliable tenants and accommodations for companies, individual and property management and valuations of all purposes.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '26,Alimosho road, Iyana Ipaja, Lagos',
  '0703 421 5599',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'The PalmView Manor Limited',
  'the-palmview-manor-limited',
  'A Lagos based hotel for luxurious lodging accommodation and banquetting facilities.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '2, Tony Anegbode Street, Victoria Island, Lagos, Nigeria',
  '08034020116',
  'approved',
  false,
  NOW(),
  NOW()
),
(
  'Westown Hotel',
  'westown-hotel',
  'Westown Hotel is a 4-star hotel located in Ikeja that provides room services for clients, bar services and range of their hotel services for the comfort of their clients.',
  (SELECT id FROM categories WHERE slug = 'accommodation' LIMIT 1),
  (SELECT id FROM states WHERE slug = 'lagos' LIMIT 1),
  '7, Sheraton-Opebi Link road, Ikeja, Lagos, Nigeria',
  '0809 810 2983',
  'approved',
  false,
  NOW(),
  NOW()
);
