// Generated by scripts/generate-blog-index.mjs. Do not edit manually.

export interface BlogPostSummary {
  slug: string
  title: string
  excerpt: string
  image: string
  date: string
  author: string
  category: string
  readTime: string
}

export const blogPostSummaries = [
  {
    "slug": "best-construction-companies-abuja",
    "title": "Best Construction Companies in Abuja (2026 Guide)",
    "excerpt": "Compare the best construction companies in Abuja for residential, commercial, road, and civil engineering projects. See top firms, selection tips, and verified contractors.",
    "image": "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1600&q=80",
    "date": "Jul 6, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Construction",
    "readTime": "14 min read"
  },
  {
    "slug": "how-to-start-real-estate-business-nigeria",
    "title": "How to Start a Real Estate Business in Nigeria",
    "excerpt": "Learn how to start a real estate business in Nigeria, choose a profitable model, register properly, find clients, build trust, and list your agency online.",
    "image": "/images/blog/abuja-real-estate-companies.svg",
    "date": "Jul 1, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Real Estate",
    "readTime": "13 min read"
  },
  {
    "slug": "local-seo-nigerian-small-businesses-rank-city",
    "title": "Local SEO for Nigerian Small Businesses: How to Rank in Your City",
    "excerpt": "Learn how Nigerian small businesses can rank for city searches, improve Google Business Profile visibility, build trusted citations, and turn local search traffic into customers.",
    "image": "/images/blog/local-seo-nigeria-hero.png",
    "date": "Jun 29, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Marketing",
    "readTime": "12 min read"
  },
  {
    "slug": "best-real-estate-companies-in-abuja",
    "title": "Best Real Estate Companies in Abuja: How to Choose a Verified Property Company",
    "excerpt": "Compare Abuja real estate companies with a buyer-first checklist covering AGIS verification, title documents, districts, red flags, reviews, and verified directory listings.",
    "image": "/images/blog/abuja-real-estate-companies.svg",
    "date": "Jun 29, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Real Estate",
    "readTime": "10 min read"
  },
  {
    "slug": "best-real-estate-companies-in-lagos",
    "title": "Best Real Estate Companies in Lagos: How to Choose a Trusted Property Firm",
    "excerpt": "A Lagos-focused guide to comparing real estate companies by neighborhood, LASRERA awareness, fee transparency, reviews, listings, and buyer protection signals.",
    "image": "/images/blog/lagos-real-estate-companies.svg",
    "date": "Jun 29, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Real Estate",
    "readTime": "10 min read"
  },
  {
    "slug": "top-law-firms-nigeria-2026",
    "title": "Top 10 Law Firms in Nigeria (2026): Corporate, Litigation & Commercial",
    "excerpt": "Looking for the best law firm in Nigeria? This guide ranks the top 10 Nigerian law firms for corporate law, litigation, oil & gas, and commercial transactions in 2026.",
    "image": "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 24, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Legal",
    "readTime": "11 min read"
  },
  {
    "slug": "best-private-hospitals-nigeria-2026",
    "title": "Best Private Hospitals in Nigeria (2026): Lagos, Abuja & Port Harcourt",
    "excerpt": "Looking for the best private hospital in Nigeria? This guide ranks the top private hospitals in Lagos, Abuja, and Port Harcourt for quality care, specialists, and facilities in 2026.",
    "image": "https://images.unsplash.com/photo-1551601651-2a8555f1a136?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 24, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Health & Medical",
    "readTime": "12 min read"
  },
  {
    "slug": "best-real-estate-companies-nigeria-2026",
    "title": "Best Real Estate Companies in Nigeria (2026): Buy, Sell & Invest",
    "excerpt": "Looking for a trusted real estate company in Nigeria? This guide ranks the top property developers, agents, and investment firms in Lagos, Abuja, and beyond for 2026.",
    "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 24, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Real Estate",
    "readTime": "13 min read"
  },
  {
    "slug": "best-it-companies-lagos-2026",
    "title": "Best IT & Technology Companies in Lagos, Nigeria (2026)",
    "excerpt": "Looking for a trusted IT company in Lagos? This guide ranks the top technology firms in Nigeria for software development, IT infrastructure, cybersecurity, and digital solutions in 2026.",
    "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 24, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Technology",
    "readTime": "12 min read"
  },
  {
    "slug": "how-to-start-food-delivery-business-in-nigeria",
    "title": "How to Start a Food Delivery Business in Nigeria (2026 Complete Guide)",
    "excerpt": "Start a food delivery business in Nigeria in 2026: startup costs in Naira, CAC registration, top platforms (Chowdeck, Glovo, HeyFood), and profit projections.",
    "image": "https://images.unsplash.com/photo-1526367790999-0150786686a2?q=80&w=2071&auto=format&fit=crop",
    "date": "Feb 23, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Business",
    "readTime": "14 min read"
  },
  {
    "slug": "best-plumbing-materials-companies-nigeria",
    "title": "Best Plumbing Materials & Companies in Nigeria (2026 Guide)",
    "excerpt": "Best plumbing materials in Nigeria (2026): top brands, PVC pipe prices in Naira, where to buy in Lagos and Abuja, and sourcing tips for construction.",
    "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 23, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Construction",
    "readTime": "10 min read"
  },
  {
    "slug": "best-plastic-manufacturing-companies-nigeria",
    "title": "Top 15 Best Plastic Manufacturing Companies in Nigeria (2026)",
    "excerpt": "Top 15 plastic manufacturing companies in Nigeria (2026): household, packaging, industrial, furniture, and pipes — with profiles, products, and contacts.",
    "image": "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 23, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Manufacturing",
    "readTime": "11 min read"
  },
  {
    "slug": "best-food-processing-companies-nigeria",
    "title": "Top 15 Best Food Processing Companies in Nigeria (2026)",
    "excerpt": "Top 15 food processing companies in Nigeria (2026): Nestle, Dangote, Flour Mills, Indomie, BUA Foods and more — with profiles, products, and industry insights.",
    "image": "https://images.unsplash.com/photo-1565118531796-763e5082d113?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 23, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Business",
    "readTime": "12 min read"
  },
  {
    "slug": "best-telecommunication-companies-nigeria",
    "title": "Best Telecommunication Companies in Nigeria (2026): MTN, Airtel, Glo & More",
    "excerpt": "Best telecom companies in Nigeria (2026): compare MTN, Airtel, Glo, and 9mobile on network coverage, data plans, call quality, and customer service.",
    "image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 23, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Technology",
    "readTime": "13 min read"
  },
  {
    "slug": "best-solar-companies-nigeria-2026",
    "title": "Best Solar Panel Installation Companies in Nigeria (2026)",
    "excerpt": "Top 12 solar panel installation companies in Nigeria (2026): prices, services, and how to choose the right solar installer for your home or business.",
    "image": "https://images.unsplash.com/photo-1497440001374-f26997328c1b?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 23, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Solar Energy",
    "readTime": "12 min read"
  },
  {
    "slug": "best-security-companies-nigeria-2026",
    "title": "Top 10 Security Companies in Nigeria (2026): Lagos, Abuja & Beyond",
    "excerpt": "Compare top security companies in Nigeria for 2026, including licensed firms in Lagos, Abuja, and Port Harcourt, plus how security companies can get listed.",
    "image": "https://images.unsplash.com/photo-1582139329536-e7284fece509?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 23, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Security Services",
    "readTime": "11 min read"
  },
  {
    "slug": "best-insurance-companies-nigeria-2026",
    "title": "Best Insurance Companies in Nigeria (2026): Motor, Health & Life",
    "excerpt": "Compare the best insurance companies in Nigeria for 2026 — Leadway, AIICO, AXA Mansard, NEM, Custodian, and more. Motor insurance prices, health plans, and what NAICOM approval means.",
    "image": "https://images.unsplash.com/photo-1556742044-3c52d6e88c62?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 23, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Insurance",
    "readTime": "13 min read"
  },
  {
    "slug": "top-10-law-firms-in-lagos",
    "title": "Top 10 Law Firms in Lagos, Nigeria (2026 Guide)",
    "excerpt": "Top 10 law firms in Lagos (2026): Chambers Tier 1 firms and specialist boutiques ranked by practice areas, fees, locations, and client reviews.",
    "image": "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=2070&auto=format&fit=crop",
    "date": "2026-02-21",
    "author": "9jaDirectory Editorial Team",
    "category": "Legal Services",
    "readTime": "14 min read"
  },
  {
    "slug": "top-10-law-firms-in-abuja",
    "title": "Top 10 Law Firms in Abuja (FCT), Nigeria (2026 Guide)",
    "excerpt": "Top 10 law firms in Abuja FCT (2026): government specialists and commercial firms ranked by SAN status, practice areas, fees, and client reviews.",
    "image": "https://images.unsplash.com/photo-1521791136064-7986c2920216?q=80&w=2070&auto=format&fit=crop",
    "date": "2026-02-21",
    "author": "9jaDirectory Editorial Team",
    "category": "Legal Services",
    "readTime": "15 min read"
  },
  {
    "slug": "top-10-real-estate-companies-in-abuja",
    "title": "Top 10 Real Estate Companies in Abuja, Nigeria (2026 Guide)",
    "excerpt": "Top 10 real estate companies in Abuja (2026): luxury and affordable developers, estate prices, key districts, and buyer tips for FCT property.",
    "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 21, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Real Estate",
    "readTime": "14 min read"
  },
  {
    "slug": "best-web-hosting-in-nigeria-2026",
    "title": "Best Web Hosting in Nigeria (2026): Editorial Top Nigerian Hosts",
    "excerpt": "Best web hosting in Nigeria 2026: editorial shortlist of top Nigerian hosts with practical selection criteria, use cases, and buyer checklist.",
    "image": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 19, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Technology",
    "readTime": "10 min read"
  },
  {
    "slug": "cac-public-search-verify-company-nigeria",
    "title": "CAC Public Search: Verify Any Nigerian Company by Name or RC Number (2026)",
    "excerpt": "CAC public search guide 2026: how to verify any Nigerian company or business name by RC number, understand search results, spot red flags, and protect yourself from fraud.",
    "image": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 18, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Business Guide",
    "readTime": "9 min read"
  },
  {
    "slug": "cac-name-search-business-verification-nigeria",
    "title": "CAC Name Search Nigeria: How to Check Business Names and Avoid Fraud (2026)",
    "excerpt": "CAC name search Nigeria 2026: how to check if a business name is available before registration, verify existing companies, and avoid scams using the CAC public search portal.",
    "image": "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 18, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Business Guide",
    "readTime": "8 min read"
  },
  {
    "slug": "company-code-nigeria-meaning-how-to-find",
    "title": "Company Code in Nigeria: Full Meaning & How to Find Your RC Number (2026)",
    "excerpt": "Company code Nigeria explained: what RC numbers, BN numbers, and IT numbers mean, how to find your company code, and how to verify any business on the CAC portal in 2026.",
    "image": "https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 18, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Business Guide",
    "readTime": "7 min read"
  },
  {
    "slug": "cac-pre-incorporation-guide-nigeria-2026",
    "title": "CAC Pre-Incorporation Nigeria: Step-by-Step Guide (2026)",
    "excerpt": "CAC pre-incorporation 2026: register your business on pre.cac.gov.ng — name reservation, form filling, document upload, payment, and what to expect after submission.",
    "image": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 18, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Business Guide",
    "readTime": "10 min read"
  },
  {
    "slug": "how-to-check-if-company-is-registered-nigeria",
    "title": "How to Check if a Company is Registered in Nigeria (2026 CAC Guide)",
    "excerpt": "How to check if a company is registered in Nigeria: four methods including the free CAC public search, status report, certified copy, and what to do if the company is not found.",
    "image": "https://images.unsplash.com/photo-1568992688065-536aad8a12f6?q=80&w=2070&auto=format&fit=crop",
    "date": "Feb 18, 2026",
    "author": "9jaDirectory Editorial Team",
    "category": "Business Guide",
    "readTime": "9 min read"
  },
  {
    "slug": "paypal-nigeria-2026-receive-payments-withdraw-naira",
    "title": "PayPal Nigeria 2026: Receive Payments & Withdraw to Naira",
    "excerpt": "PayPal Nigeria 2026 guide: receive payments, withdraw to Naira, account setup, fees, limits & top alternatives for Nigerian freelancers.",
    "image": "https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=2070&auto=format&fit=crop",
    "date": "Jan 28, 2026",
    "author": "9jaDirectory Fintech Team",
    "category": "Finance",
    "readTime": "12 min read"
  },
  {
    "slug": "local-lead-generation-mistakes-nigeria-2025",
    "title": "Local Lead Generation Mistakes: 7 Errors That Kill Customers in Nigeria (2025)",
    "excerpt": "Local lead generation mistakes can drain customers. Learn 7 errors Nigerian businesses make and how a Nigeria business directory listing drives calls and visits.",
    "image": "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=2070&auto=format&fit=crop",
    "date": "Jan 8, 2026",
    "author": "9jaDirectory Marketing Team",
    "category": "Marketing",
    "readTime": "12 min read"
  },
  {
    "slug": "best-banks-small-business-nigeria-comparison-2025",
    "title": "Top 10 Banks for Small Business in Nigeria (2025): Rates & Fees",
    "excerpt": "Top 10 banks for small business in Nigeria 2025: Compare Moniepoint, Kuda, OPay, GTBank & Access Bank on interest rates, fees & account requirements.",
    "image": "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1600&q=80",
    "date": "Dec 20, 2025",
    "author": "9jaDirectory Editorial Team",
    "category": "Finance",
    "readTime": "10 min read"
  },
  {
    "slug": "how-to-get-business-loan-without-collateral-nigeria-2025",
    "title": "How to Get a Business Loan Without Collateral in Nigeria (2025)",
    "excerpt": "Business loan without collateral Nigeria: compare top lenders, rates, and requirements for SMEs, plus tips to get fast approval.",
    "image": "https://images.unsplash.com/photo-1579621970795-87facc2f976d?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 30, 2025",
    "author": "9jaDirectory Finance Team",
    "category": "Finance",
    "readTime": "16 min read"
  },
  {
    "slug": "how-to-start-blogging-content-business-nigeria-2025",
    "title": "How to Start a Blogging Business in Nigeria (2025 Guide)",
    "excerpt": "How to start blogging in Nigeria: pick a niche, set up your blog, and monetize with ads, services, affiliates, and email.",
    "image": "https://images.unsplash.com/photo-1499750310107-5fef28a66643?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 29, 2025",
    "author": "9jaDirectory Business Team",
    "category": "Business",
    "readTime": "12 min read"
  },
  {
    "slug": "how-to-start-ecommerce-business-nigeria-2025",
    "title": "How to Start an E-Commerce Business in Nigeria (2025): Complete Setup Guide",
    "excerpt": "Start an e-commerce business in Nigeria: choose products, set up a store, payments, and get your first sales with marketing basics.",
    "image": "https://images.unsplash.com/photo-1557821552-17105176677c?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 28, 2025",
    "author": "9jaDirectory Commerce Team",
    "category": "Business",
    "readTime": "13 min read"
  },
  {
    "slug": "small-business-grants-nigeria-2025",
    "title": "Top 10 Small Business Grants in Nigeria for 2025 (Apply Now)",
    "excerpt": "Small business grants in Nigeria for 2025: top government and private programs, eligibility, and how to apply with deadlines.",
    "image": "https://images.unsplash.com/photo-1553729459-efe14ef6055d?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 27, 2025",
    "author": "9jaDirectory Editorial Team",
    "category": "Funding",
    "readTime": "10 min read"
  },
  {
    "slug": "how-to-start-consulting-business-nigeria-2025",
    "title": "How to Start a Consulting Business in Nigeria (2025): ₦200K-₦2M Per Project",
    "excerpt": "How to start consulting business in Nigeria: pick a niche, price your service, and win high-value clients with a simple proposal process.",
    "image": "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 27, 2025",
    "author": "9jaDirectory Professional Services Team",
    "category": "Business",
    "readTime": "14 min read"
  },
  {
    "slug": "how-to-start-import-export-business-nigeria-2025",
    "title": "How to Start an Import/Export Business in Nigeria (2025): ₦5M-₦50M Potential",
    "excerpt": "Complete guide to starting import/export business in Nigeria. Learn regulations, customs, documentation, shipping, and how to make ₦2M-₦10M per shipment.",
    "image": "https://images.unsplash.com/photo-1453614512568-c4024d13c247?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 26, 2025",
    "author": "9jaDirectory Trade Team",
    "category": "Business",
    "readTime": "12 min read"
  },
  {
    "slug": "top-business-listing-sites-in-nigeria-2025",
    "title": "Top Business Listing Sites in Nigeria to Grow Your Visibility (2025 Guide)",
    "excerpt": "Business listing sites in Nigeria help you rank and get customers. See the top 10 directories for 2025 and how to use them for local SEO.",
    "image": "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 25, 2025",
    "author": "9jaDirectory Editorial Team",
    "category": "Marketing",
    "readTime": "10 min read"
  },
  {
    "slug": "start-pos-business-nigeria-cost-profit-2025",
    "title": "How to Start a POS Business in Nigeria: Cost & Profit Breakdown (2025)",
    "excerpt": "POS business Nigeria guide: startup costs, Moniepoint vs OPay vs PalmPay, daily profit range, location tips, and setup checklist.",
    "image": "https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1600&q=80",
    "date": "Nov 25, 2025",
    "author": "Musa Ibrahim",
    "category": "Business Guide",
    "readTime": "10 min read"
  },
  {
    "slug": "how-to-start-logistics-delivery-business-nigeria-2025",
    "title": "How to Start a Logistics Business in Nigeria (2025): ₦500K-₦2M Monthly",
    "excerpt": "Logistics business Nigeria guide: startup costs, delivery model, client niches, and how to reach N500K-N2M monthly revenue.",
    "image": "https://images.unsplash.com/photo-1526367790999-0150786686a2?q=80&w=2071&auto=format&fit=crop",
    "date": "Nov 25, 2025",
    "author": "9jaDirectory Services Team",
    "category": "Business",
    "readTime": "10 min read"
  },
  {
    "slug": "mini-importation-nigeria-china-guide-2025",
    "title": "Mini Importation Guide: How to Import from China to Nigeria (2025)",
    "excerpt": "Mini importation Nigeria made simple: buy from 1688 or Alibaba, ship to Nigeria, and start with N50,000 using a product checklist.",
    "image": "https://images.unsplash.com/photo-1578575437130-527eed3abbec?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 24, 2025",
    "author": "Chinyere Okeke",
    "category": "Business Guide",
    "readTime": "12 min read"
  },
  {
    "slug": "how-to-start-beauty-salon-business-nigeria-2025",
    "title": "How to Start a Beauty & Salon Business in Nigeria (2025): ₦300K-₦2M Startup",
    "excerpt": "Launch a profitable beauty or salon business in Nigeria. Comprehensive guide covering salon setup, services, pricing, marketing, and reaching ₦500K/month.",
    "image": "https://images.unsplash.com/photo-1570158268183-d296b2892211?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 24, 2025",
    "author": "9jaDirectory Beauty Team",
    "category": "Business",
    "readTime": "11 min read"
  },
  {
    "slug": "business-registration-nigeria-guide",
    "title": "The Ultimate Guide to Business Registration in Nigeria (2025 Update)",
    "excerpt": "Business registration Nigeria guide: CAC steps, costs, and requirements for business name vs limited company, plus how to get your TIN.",
    "image": "https://images.unsplash.com/photo-1497366412874-3415097a27e7?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 23, 2025",
    "author": "9jaDirectory Editorial Team",
    "category": "Business Guide",
    "readTime": "10 min read"
  },
  {
    "slug": "how-to-start-food-processing-snacks-business-nigeria-2025",
    "title": "How to Start a Food Processing & Snacks Business in Nigeria (2025): ₦500K-₦3M",
    "excerpt": "Food processing business Nigeria guide: snacks, plantain chips, and sauces with startup cost, licensing basics, and growth tips.",
    "image": "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1400&q=80",
    "date": "Nov 23, 2025",
    "author": "9jaDirectory Food Business Team",
    "category": "Business",
    "readTime": "12 min read"
  },
  {
    "slug": "reits-nigeria-investment-guide-2025",
    "title": "Real Estate Investment Trusts (REITs) in Nigeria: 2025 Investment Guide",
    "excerpt": "REITs in Nigeria let you invest in property with small capital. Learn how to buy, earn dividends, and start in 2025 with a step-by-step guide.",
    "image": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 22, 2025",
    "author": "Chinedu Okonkwo",
    "category": "Investment",
    "readTime": "11 min read"
  },
  {
    "slug": "how-to-start-agribusiness-farming-nigeria-2025",
    "title": "How to Start an Agribusiness in Nigeria (2025): ₦1M-₦10M+ Annual Profit",
    "excerpt": "Complete guide to starting profitable agribusiness in Nigeria. Poultry, crop farming, fish farming, snail farming. ₦500K-₦5M startup. Scale to ₦5M-₦50M.",
    "image": "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=1400&q=80",
    "date": "Nov 22, 2025",
    "author": "9jaDirectory Agriculture Team",
    "category": "Business",
    "readTime": "14 min read"
  },
  {
    "slug": "foodstuff-export-business-nigeria-guide",
    "title": "How to Start a Profitable Foodstuff Export Business in Nigeria (2025)",
    "excerpt": "Foodstuff export business Nigeria guide: NEPC registration, NAFDAC compliance, logistics, and finding overseas buyers with pricing tips.",
    "image": "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 21, 2025",
    "author": "9jaDirectory Editorial Team",
    "category": "Business Guide",
    "readTime": "9 min read"
  },
  {
    "slug": "top-10-investment-opportunities-lagos",
    "title": "Top 10 Investment Opportunities in Lagos (2025): Where Smart Money Goes",
    "excerpt": "Investment opportunities in Lagos for 2025: real estate, fintech, and agribusiness with ROI ranges, entry costs, and location tips.",
    "image": "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1400&q=80",
    "date": "Nov 20, 2025",
    "author": "Sarah Adebayo",
    "category": "Investment",
    "readTime": "10 min read"
  },
  {
    "slug": "solar-power-solutions-nigeria-business-prices",
    "title": "Solar Power Solutions for Nigerian Businesses: Prices & Installers (2025)",
    "excerpt": "Solar power Nigeria pricing for businesses: 5kVA and 10kVA system costs, battery options, and top installers for 2025 with sizing tips.",
    "image": "https://images.unsplash.com/photo-1509391366360-2e959784a276?q=80&w=2072&auto=format&fit=crop",
    "date": "Nov 20, 2025",
    "author": "9jaDirectory Tech Team",
    "category": "Technology",
    "readTime": "12 min read"
  },
  {
    "slug": "high-paying-digital-skills-nigeria-2025",
    "title": "Top 10 High-Paying Digital Skills to Learn in Nigeria in 2025",
    "excerpt": "High paying digital skills Nigeria 2025 list: software, data, design, and cybersecurity with income potential and where to learn them.",
    "image": "https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 19, 2025",
    "author": "9jaDirectory Careers",
    "category": "Technology",
    "readTime": "12 min read"
  },
  {
    "slug": "digital-marketing-strategies-small-business",
    "title": "Effective Digital Marketing Strategies for Small Businesses in Nigeria (2025)",
    "excerpt": "Digital marketing Nigeria guide for SMEs: social media, SEO, email, and low-cost tactics to grow customers without big budgets.",
    "image": "https://images.unsplash.com/photo-1533750349088-cd871a92f312?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 18, 2025",
    "author": "Tunde Bakare",
    "category": "Marketing",
    "readTime": "8 min read"
  },
  {
    "slug": "dropshipping-nigeria-zero-capital-guide",
    "title": "Dropshipping in Nigeria: How to Start with Zero Capital (2025)",
    "excerpt": "Learn how to start dropshipping in Nigeria in 2025: pick a niche, find suppliers, sell on WhatsApp/Instagram/Jumia, and deliver without holding stock.",
    "image": "https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 18, 2025",
    "author": "9jaDirectory E-commerce Team",
    "category": "Business",
    "readTime": "10 min read"
  },
  {
    "slug": "top-coworking-spaces-lagos-2025",
    "title": "Top Co-working Spaces in Lagos for Freelancers & Startups (2025)",
    "excerpt": "Co-working spaces Lagos guide for 2025: pricing, amenities, and best hubs in Ikeja, Yaba, and Lekki, plus who each space suits.",
    "image": "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=2069&auto=format&fit=crop",
    "date": "Nov 16, 2025",
    "author": "9jaDirectory Tech Team",
    "category": "Technology",
    "readTime": "9 min read"
  },
  {
    "slug": "understanding-tax-compliance-nigeria",
    "title": "Tax Compliance in Nigeria: Complete 2025 Guide for SMEs",
    "excerpt": "A 2025 step-by-step guide to tax compliance in Nigeria for SMEs: VAT, CIT, PAYE, WHT, deadlines, penalties, and filing tips to stay audit-ready.",
    "image": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1400&q=80",
    "date": "Nov 15, 2025",
    "author": "Ngozi Uche",
    "category": "Finance",
    "readTime": "7 min read"
  },
  {
    "slug": "networking-events-lagos-2025",
    "title": "Networking Events in Lagos: Where to Meet Investors & Partners (2025)",
    "excerpt": "Networking events Lagos 2025: where to meet investors, how to network, and follow-up tips that convert for founders and SMEs.",
    "image": "https://images.unsplash.com/photo-1515187029135-18ee286d815b?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 15, 2025",
    "author": "9jaDirectory Events",
    "category": "Lifestyle",
    "readTime": "9 min read"
  },
  {
    "slug": "scuml-registration-guide-dnfi-nigeria",
    "title": "SCUML Registration Guide for DNFI Businesses (2025 Update)",
    "excerpt": "SCUML registration guide for DNFI businesses: requirements, steps, timelines, and common mistakes to avoid, plus documents you need.",
    "image": "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 14, 2025",
    "author": "9jaDirectory Legal Team",
    "category": "Legal",
    "readTime": "11 min read"
  },
  {
    "slug": "cac-business-registration-nigeria-guide-2025",
    "title": "How to Register a Company in Nigeria (CAC Step-by-Step 2025)",
    "excerpt": "How to register a company in Nigeria (CAC 2025): business name vs LTD, required documents, CRP portal steps, fees, and timelines.",
    "image": "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 13, 2025",
    "author": "9jaDirectory Legal Team",
    "category": "Legal",
    "readTime": "14 min read"
  },
  {
    "slug": "remote-work-tools-productivity",
    "title": "Essential Tools for Remote Work Productivity in 2025: The Complete Guide",
    "excerpt": "Remote work tools for 2025: top picks for communication, project management, and time tracking to keep teams productive.",
    "image": "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1400&q=80",
    "date": "Nov 12, 2025",
    "author": "Emmanuel Kalu",
    "category": "Productivity",
    "readTime": "8 min read"
  },
  {
    "slug": "best-payment-gateways-nigeria-2025",
    "title": "Best Payment Gateways for Nigerian Businesses: Paystack vs Flutterwave (2025)",
    "excerpt": "Best payment gateway in Nigeria comparison: Paystack vs Flutterwave vs Monnify on fees, payouts, and features for SMEs and ecommerce.",
    "image": "https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1600&q=80",
    "date": "Nov 12, 2025",
    "author": "9jaDirectory Fintech Team",
    "category": "Technology",
    "readTime": "11 min read"
  },
  {
    "slug": "social-media-marketing-nigeria-guide-2025",
    "title": "Ultimate Guide to Social Media Marketing for Nigerian SMEs (2025)",
    "excerpt": "A complete 2025 social media marketing playbook for Nigerian SMEs: content strategy, ads, WhatsApp funnels, and how to turn followers into customers.",
    "image": "https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1974&auto=format&fit=crop",
    "date": "Nov 11, 2025",
    "author": "9jaDirectory Marketing",
    "category": "Marketing",
    "readTime": "14 min read"
  },
  {
    "slug": "starting-agriculture-business-nigeria",
    "title": "How to Start an Agriculture Business in Nigeria (2025): Poultry, Fish & Crops",
    "excerpt": "Agriculture business Nigeria guide for 2025: poultry, fish, and crops, startup costs, funding options, and steps to profit.",
    "image": "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=1400&q=80",
    "date": "Nov 10, 2025",
    "author": "Musa Ibrahim",
    "category": "Agriculture",
    "readTime": "14 min read"
  },
  {
    "slug": "business-ideas-students-nigeria-2025",
    "title": "Top 10 Business Ideas for Students in Nigeria (Low Capital 2025)",
    "excerpt": "10 realistic low-capital business ideas for Nigerian students in 2025—plus how to start, what to charge, and how to find customers without hurting your grades.",
    "image": "https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 10, 2025",
    "author": "9jaDirectory Careers",
    "category": "Business Guide",
    "readTime": "14 min read"
  },
  {
    "slug": "nafdac-registration-requirements-nigeria-2025",
    "title": "How to Get NAFDAC Registration for Your Product (2025 Guide)",
    "excerpt": "NAFDAC registration for your product in 2025: requirements, NAPAMS portal steps, timelines, costs, and how to avoid delays.",
    "image": "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=2070&auto=format&fit=crop",
    "date": "Nov 09, 2025",
    "author": "9jaDirectory Legal Team",
    "category": "Legal",
    "readTime": "13 min read"
  }
] as const satisfies readonly BlogPostSummary[]
